### ISSUE TITLE
支持xcode8.3的xpath定位吗

### ISSUE THREAD

**Issue by mylove132** [macaca-sample/macaca-java-biz-sample#1]
Response content:{"sessionId":"","status":7,"value":""}
An element could not be located on the page using the given search parameters.
2017-06-21 15:16:57,异常捕捉|An element could not be located on the page using the given search parameters.

200
Response content:{"sessionId":"ee2e9b22-72d8-49c8-a88e-14eda4aca742","status":0}
The command executed successfully.

**Comment by xudafeng** [comment]
升到9吧
